---
title: "R Notebook"
output: html_notebook
---

```{r}

rm(list=ls())
library(tidyverse)
library(readr)
library(lubridate)

# define some functions
get.data <- function(dir, YEAR, ff){
  FILES <- list.files(paste0(dir, "/", YEAR))
  all.lines <- read_lines(file = paste0(dir, "/", YEAR, "/", FILES[ff]))
  event.code <- str_sub(all.lines, start = 5, end = 5)
  COMMENTS <- which(event.code == "C")
  
  if(length(COMMENTS)>0){
    data <- read.table(text = all.lines[-COMMENTS],
                       fill=T,
                       na.strings = "",
                       stringsAsFactors = F,
                       col.names = paste0("V",1:16))
  }else{
    data <- read.table(text = all.lines,
                       fill=T,
                       na.strings = "",
                       stringsAsFactors = F,
                       col.names = paste0("V",1:16))
    
  }
  
  # Files with extensive comments in sightings are problematic because they get split into multiple lines. 
  # We need to pull out lines that contain only numeric V1 (when they are converted into numeric)
  
  data <- data[!is.na(as.numeric(data$V1)),]
  
  Starts <- which(data$V2=="B") #Find all start times
  Ends <- which(data$V2=="E") #Find all end times
  
  if(length(Starts)>0 & length(Ends)>0){
    #Make an array to hold the time differences of starts and ends
    Diffs <- matrix(NA, ncol=length(Ends), nrow=length(Starts)) 
    
    for(t in 1:length(Starts)){
      #Subtract all end times from each start time (if an end time is less than 90 seconds 
      # before a start time, that's probably an error)
      # TE: I added [t] to Ends in the following line. I think it's needed. NO... 
      # Ends does not need the subscript. 
      Diffs[t,] <- seconds(hms(data[Starts[t],4])) - seconds(hms(data[Ends,4])) 
    }
    
    #Select the differences that are likely errors (End, <90 seconds, Start. Oops!)
    Oops <- which(Diffs >=0 & Diffs<91,arr.ind = T) 
    
    if(length(Oops)>0){ #If there are any suspect errors, remove them from the data file
      data <- data[-c(Starts[Oops[1]], (Starts[Oops[1]]+1), Ends[Oops[2]]),]
    }
  }
  
  BeginDay <- mdy(data$V3) - mdy(paste0("11/30/", (YEAR - 1)))
  # Decimal hour of shift start time
  BeginHr <- hour(hms(data$V4)) + minute(hms(data$V4))/60
  
  data %>% mutate(begin = as.numeric(BeginDay) + BeginHr/24) -> data
  return(data)
}

get.shift <- function(YEAR, data, i){
  # if no matching Es, creat them:
  Shifts.begin <- which(data$V2 %in% c("P", "E"))
  #Shifts.end <- which(data$V2 %in% "E")

  max.shifts <- length(Shifts.begin) - 1
  #Only use the first observer for model random effect
  Observer <- data[Shifts.begin[i], 5] 
  # Days since Nov 30th of the previous year
  BeginDay <- mdy(data[Shifts.begin[i], 3]) - mdy(paste0("11/30/", (YEAR - 1)))
  # Decimal hour of shift start time
  BeginHr <- (hour(hms(data[Shifts.begin[i], 4])) + (minute(hms(data[Shifts.begin[i], 4]))/60)) 
  # Decimal hour of next shift start time
  if (i < max.shifts){
    NextBeginHr <- (hour(hms(data[Shifts.begin[i+1], 4])) + (minute(hms(data[Shifts.begin[i+1], 4]))/60)) 
  } else {
    NextBeginHr <- (hour(hms(data[which(data$V2 %in% "E"), 4])) + 
                      (minute(hms(data[which(data$V2 %in% "E"), 4]))/60)) + 0.00001
  }
  # End time is just before next start time (replicating J Durban's calculations)
  EndHr <- NextBeginHr - 0.00001 
  # Beginning time as a decimal day
  Begin <- as.numeric(BeginDay) + (BeginHr/24) 
  #End time as a decimal day
  End <- as.numeric(BeginDay) + (EndHr/24)
  BFs <- as.numeric(data[Shifts.begin[i]:(Shifts.begin[i+1]-1), 12])
  if (sum(!is.na(BFs)) == 0){
    BF <- NA
  } else {
    BF <- max(BFs, na.rm=T)
  }
  
  #Visibility (maximum from watch period)
  VSs <- as.numeric(data[Shifts.begin[i]:(Shifts.begin[i+1]-1), 13])
  if (sum(!is.na(VSs)) == 0){
    VS <- NA 
  } else {
    VS <- max(VSs, na.rm=T) 
  }
  
  # if still NA
  if (is.na(BF)) {BF <- data[Shifts.begin[i]+1, 5]}
  if (is.na(VS)) {VS <- data[Shifts.begin[i]+1, 6]}

  Spillover <- vector(length = 0)
  if (i < max.shifts){
    # Groups = Observers. Only the first (primary) observer is considered (V5)
    GroupsThisWatch <- data[Shifts.begin[i]:(Shifts.begin[i+1]-1),] %>% # Group numbers from this watch period
      filter(V2 == "S") %>%
      distinct(V5) %>%
      pull()
    
    GroupsNextWatch <- data[Shifts.begin[i+1]:(Shifts.begin[i+2]-1),] %>% # Group numbers from next watch period
      filter(V2 == "S") %>%
      distinct(V5) %>%
      pull()
    
    # Which groups from watch i were also observed in watch i+1? They should be excluded from i and counted in i+1
    Spillover <- GroupsThisWatch[GroupsThisWatch %in% GroupsNextWatch] 
    
  }
  
    
  if(length(Spillover > 0)){ #if there are groups that spill over into following watch, 
    # figure out if there were any sightings that need to be considered:
    sub.data <- data[(Shifts.begin[i]):(Shifts.begin[i+1]-1),] %>% 
      filter(V2 == "S", !(V5 %in% Spillover), V14 != "North")
    
    if (nrow(sub.data) > 0){
      N <- sub.data %>%
        group_by(V5) %>% #group by the whale group number
        select(V5, V9) %>%
        summarize(N = max(as.numeric(V9), na.rm = T)) %>% 
        select(N)  %>% sum()
    } else {
      N <- 0
    }
    
  } else {   # if there were no spillover
    sub.data <- data[Shifts.begin[i]:(Shifts.begin[i+1]-1),]  %>%  
      filter(V2 == "S", V14 != "North")
      
    if (nrow(sub.data) > 0){
      N <- sub.data %>%
        group_by(V5) %>% #group by the whale group number
        select(V5, V9) %>%
        summarize(N = max(as.numeric(V9), na.rm = T)) %>% 
        select(N)  %>% sum()
    } else {
      N <- 0
    }
    
  }
  
  out.list <- list(out.df = data.frame(begin=as.numeric(Begin),
                                       end=as.numeric(End),
                                       dur = as.numeric(End) - as.numeric(Begin),
                                       bf=as.numeric(BF),
                                       vs=as.numeric(VS),
                                       n = N,
                                       obs=as.character(Observer),
                                       i=i,
                                       BeginHr = BeginHr,
                                       BeginDay = BeginDay),
                   data = sub.data)
  return( out.list )
}
```

Get data and start looking at them:

```{r}
Tomo.out <- readRDS("RData/out_2022_Tomos.rds")
Josh.out <- readRDS("RData/out_2022_Joshs.rds")
FinalData.Josh <- Josh.out$FinalData %>% mutate(v = "J")
FinalData.Tomo <- Tomo.out$FinalData %>% mutate(v = "T")
FinalData.Both <- rbind(FinalData.Josh, FinalData.Tomo)

dim(FinalData.Josh)
dim(FinalData.Tomo)

FinalData.Josh %>% 
  group_by(ff) %>% 
  summarize(nrow = n()) -> Josh.summary

FinalData.Tomo %>% 
  group_by(ff) %>% 
  summarize(nrow = n()) -> Tomo.summary

Tomo.summary %>% left_join(Josh.summary, by = "ff") %>%
  mutate(dif = nrow.x - nrow.y) -> TomoVsJosh_n

#%>% filter(abs(dif) > 0) 
comp.df <- data.frame(nrow = nrow(Tomo.out$FinalData), ncol = 6) 
#begin = NA, end = NA, max.bf = NA, max.vs = NA, total.n = NA)
Fs <- unique(FinalData.Tomo$ff)
for (f in 1:length(Fs)){
  J1 <- Josh.out$FinalData %>% filter(ff == Fs[f])
  T1 <- Tomo.out$FinalData %>% filter(ff == Fs[f])
  
  comp.df[f,1] <- J1$begin[1] - T1$begin[1]
  comp.df[f,2] <- J1$end[1] - T1$end[1]
  comp.df[f,3] <- max(J1$bf) - max(T1$bf)
  comp.df[f,4] <- max(J1$vs) - max(T1$vs)
  comp.df[f,5] <- sum(J1$n) - sum(T1$n)
  comp.df[f,6] <- Fs[f]

}

```


vs is different for files 6 and 39.  START HERE 2022-03-09


```{r}
ggplot(data = FinalData.Both) +
  geom_point(aes(x = begin, y = end, color = v))

delta.begin <- FinalData.Josh$begin - FinalData.Tomo$begin
sum(abs(delta.begin))

#No difference between the two.

```

