---
title: "R Notebook"
output: html_notebook
---

This notebook describes abundance estimation of gray whales using a modified version of Durban's WinBUGS code and Ver2.0 data extraction method. In this version, I replace the normal/spline curves with GAMs. 


Set up libraries

```{r}
rm(list=ls())
library(abind)
library(jagsUI)
library(tidyverse)
library(bayesplot)
library(mgcv)
# PARAMETER NAME TRANSFERS:

# JOSH     JOHN
#    Spline 
# b.sp     b1 
# beta.sp  beta1
# X.sp     X1

# # periods for the 6 survey years
periods <-c(136, 135, 164, 178, 179, 151)

# Observer list gets updated as new observers are added. 
obs.list <- read.csv("Data/Observer list.csv", header = T) 
colnames(obs.list) <- c("obs", "ID")
seasons <- c("2006/2007", "2007/2008", "2009/2010", "2010/2011", 
             "2014/2015", "2015/2016", "2019/2020", "2021/2022")

x <- length(seasons)

# CHANGE THIS LINE BACK
#Ver2.results <- readRDS(paste0("RData/WinBUGS_", x, "yr_v2.rds"))
Ver2.results <- readRDS(paste0("RData/WinBUGS_", x, "yr_100k_v2.rds"))

jags.data <- Ver2.results$jags.data
jags.params <- c("lambda","OBS.RF","OBS.Switch",
                "BF.Switch","BF.Fixed","VS.Switch",
                "VS.Fixed","mean.prob","mean.prob.com",
                "mean.prob.sp","BF.Fixed.com",
                "BF.Fixed.sp","VS.Fixed.com",
                "VS.Fixed.sp",
                "Corrected.Est","Raw.Est","z",
                "com","sp","Daily.Est","mean.beta",
                "beta.sigma","beta","beta.sp","b.sp","sd.b.sp")

MCMC.params <- list(n.samples = 20000,
                   n.thin = 50,
                   n.burnin = 5000,
                   n.chains = 5)

# ni <- 100000
# nt <- 80
# nb <- 60000
# nc <- 3
N_inits <- Ver2.results$N_inits
inits.list <- list(mean.prob = 0.5,
                   BF.Fixed = 0,
                   VS.Fixed = 0,
                   mean.prob.sp = 0.5,
                   BF.Fixed.sp = 0,
                   VS.Fixed.sp = 0,
                   mean.prob.com = 0.5,
                   BF.Fixed.com = 0,
                   VS.Fixed.com = 0,
                   mean.beta = c(0,0,0), #mean.beta = c(5,0.14,-3.5),
                   beta.sigma = c(1,1,1),#beta.sigma = c(7,7,7),
                   BF.Switch = 1,
                   VS.Switch = 1,
                   OBS.Switch = 1,
                   sigma.Obs = 1,
                   BF.Switch.sp = 1,
                   VS.Switch.sp = 1,
                   OBS.Switch.sp = 1,
                   sigma.Obs.sp = 1,
                   BF.Switch.com = 1,
                   VS.Switch.com = 1,
                   OBS.Switch.com = 1,
                   sigma.Obs.com = 1,
                   N = N_inits,
                   N.com = N_inits,
                   N.sp = N_inits,
                   #z = matrix(1,nrow=90,ncol=6),
                   beta.sp = array(data=0, dim=c(2,x)),
                   sd.b.sp = rep(1, times = x), #c(1,1,1,1,1,1),
                   z = matrix(1, nrow=90, ncol= x))
  
```

Create GAM part using jagam function. The daily mean is a smooth function of days (1:90)

```{r}
daily.effort <- daily.counts <- daily.N <- matrix(nrow = 90, ncol = x)
Watch.Length <- Ver2.results$jags.data$Watch.Length
day.mat <- Ver2.results$jags.data$day
ns <- rbind(Ver2.results$jags.data$n[,1,], matrix(NA, nrow = 2, ncol = x))

for (y in 1:x){
  for (j in 1:90){
    if (j == 1 | j == 90){
      daily.effort[j,y] <- 0
      daily.counts[j,y] <- 0
      daily.N[j,y] <- 0
    } else {
      daily.effort[j, y] <- sum(Watch.Length[day.mat[,y] == j, y], na.rm = T)
      daily.counts[j, y] <- sum(ns[day.mat[,y] == j, y], na.rm = T)
      daily.N[j, y] <- daily.counts[j,y]/daily.effort[j,y]
      
    }
  }
}
  
daily.N.df <- data.frame(daily.N) 
colnames(daily.N.df) <- seasons
daily.N.df %>% pivot_longer(everything(),
                            names_to = "Season", 
                            values_to = "N") %>%  
  arrange(Season) -> daily.N.df.long

daily.N.df.long$days <- rep(1:90, times = x)
daily.N.df.long$year <- factor(rep(1:x, each = 90))

daily.N.df.long %>% select(-Season) %>%
  na.omit() -> daily.N.df.long.noNA

jags.gam <- jagam(N ~ s(days, by = year), data = daily.N.df.long.noNA,
                  file = "models/Model_dailyN_GAM_1_JAGS.txt")

## Try running this code: runs fine. 
# jm.gam <- jags(data = jags.gam$jags.data,
#                inits = rep(list(jags.gam$jags.ini), 3),
#                parameters.to.save = c("mu", "b", "scale", "rho"),
#                model.file = "models/Model_dailyN_GAM_1_JAGS.txt",
#                n.chains = 3, n.thin = 10, n.burnin = 1000,
#                n.iter = 5000, DIC = T, parallel = T)
if (!file.exists("RData/dailyN_GAM_1_JAGS_out.rds")){
  jm <- rjags::jags.model("models/Model_dailyN_GAM_1_JAGS.txt",
                          data = jags.gam$jags.data,
                          inits = rep(list(jags.gam$jags.ini), 
                                      MCMC.params$n.chains),
                          n.chains = MCMC.params$n.chains,
                          n.adapt = MCMC.params$n.burnin)
  
  jm.gam2 <- rjags::jags.samples(jm, c("mu", "b", "scale", "rho"),
                                 n.iter = MCMC.params$n.samples, 
                                 n.thin = MCMC.params$n.thin)
  
  saveRDS(list(jm = jm, jm.gam2 = jm.gam2),
          file = "RData/dailyN_GAM_1_JAGS_out.rds")
  
} else {
  jm.fit <- readRDS("RData/dailyN_GAM_1_JAGS_out.rds")
  jm <- jm.fit$jm
  jm.gam2 <- jm.fit$jm.gam2
}

jam <- sim2jam(jm.gam2, jags.gam$pregam)
#plot(jam)
pred.data <- data.frame(days = rep(1:90, x),
                        year = rep(1:x, each = 90))

Xp <- predict(jam, newdata = pred.data, type = "lpmatrix")
pred <- predict(jam, newdata = pred.data)
pred.data$prediction <- pred

# SEnd in the prediction values - they are now fixed
# this is kinda like using cut function, no? 
jags.data$Xp <- Xp
jags.data$col.idx <- rbind(rep(1, times = x), 
                           matrix(2:73, ncol = x))

ggplot(pred.data) +
  geom_path(aes(x = days, y = prediction)) +
  facet_wrap(vars(year))
```


Run jags if it hasn't been run..

```{r}
if (!file.exists(paste0("RData/JAGS_GAM_Nmix_", x, "yr_v2.rds"))){
  
  #Run time: 
  Start_Time<-Sys.time()
  #load.module("glm") # Simon Wood's example shows this but it doesn't work 
  jm <- jags(jags.data,
             inits = rep(list(inits.list), MCMC.params$n.chains),
             parameters.to.save= jags.params,
             model.file = 'models/Model_GAM_Nmix_JAGS.txt',
             n.chains = MCMC.params$n.chains,
             n.burnin = MCMC.params$n.burnin,
             n.thin = MCMC.params$n.thin,
             n.iter = MCMC.params$n.samples,
             DIC = T, parallel=T)
    
  Run_Time <- Sys.time() - Start_Time
  Ver2.results <- list(jags.data = jags.data,
                       N_inits = N_inits,
                       JAGS_out = jm,
                       Run_Time = Run_Time)
  saveRDS(Ver2.results, 
          paste0("RData/JAGS_GAM_Nmix_", x, "yr_v2.rds"))
  
} else {
  Ver2.results <- readRDS(paste0("RData/JAGS_GAM_Nmix_", x, "yr_v2.rds"))
  
}
```


Make some plots:

```{r}
seasons <- c("2006/2007", "2007/2008", "2009/2010", "2010/2011", 
             "2014/2015", "2015/2016", "2019/2020", "2021/2022")

# Extract estimated counts
Daily.Est <- Ver2.results$JAGS_out$sims.list$Daily.Est
sp <- Ver2.results$JAGS_out$sims.list$sp
com <- Ver2.results$JAGS_out$sims.list$com
Corrected.Est <- Ver2.results$JAGS_out$sims.list$Corrected.Est

# Each one of them is (# samples) x (90 days) x (# years)
# To plot them using ggplot's facet, I need to convert
# these into 2D dataframes of statistics (upper and lower 
# CIs, median, etc.)
# Daily.Est.list <- sp.list <- com.list <- vector(mode = "list", 
#                                                 length = dim(Daily.Est)[3])
# 
# Daily.Est.UCIs <- Daily.Est.LCIs <- vector(mode = "list",
#                                            length = dim(Daily.Est)[3])

stats.list <- vector(mode = "list",
                     length = dim(Daily.Est)[3])

for (k in 1:dim(Daily.Est)[3]){
  # Daily.Est.list[[k]] <- Daily.Est[,,k]
  # Daily.Est.UCIs[[k]] <- apply(Daily.Est[,,k],2,quantile,0.975)
  # Daily.Est.LCIs[[k]] <- apply(Daily.Est[,,k],2,quantile,0.275)
  # 
  # sp.list[[k]] <- sp[,,k]
  # com.list[[k]] <- com[,,k]
  
  stats.list[[k]] <- data.frame(Daily.Est.median = apply(Daily.Est[,,k], 2,
                                                         median),
                                Daily.Est.LCL = apply(Daily.Est[,,k], 2,
                                                      quantile,0.275),
                                Daily.Est.UCL = apply(Daily.Est[,,k], 2,
                                                      quantile,0.975),
                                sp.median = apply(exp(sp[,,k]), 2,
                                                  median),
                                sp.LCL = apply(exp(sp[,,k]), 2,
                                               quantile,0.025),
                                sp.UCL = apply(exp(sp[,,k]), 2,
                                               quantile,0.975),
                                com.median = apply(exp(com[,,k]), 2,
                                                   median),
                                com.LCL = apply(exp(com[,,k]), 2,
                                                quantile,0.025),
                                com.UCL = apply(exp(com[,,k]), 2,
                                                quantile,0.975),
                                #total.median = apply(exp(sp[,,k]), 1, sum),
                                days = 1:dim(Daily.Est)[2],
                                year = seasons[k])
}

all.stats <- do.call("rbind", stats.list) %>% group_by(year)

ggplot(data = all.stats) + 
  geom_line(aes(x = days, y = sp.median)) + 
  geom_line(aes(x = days, y = com.median)) +
  geom_ribbon(aes(x = days, 
                  ymin = sp.LCL, 
                  ymax = sp.UCL),
              fill = "orange", 
              alpha = 0.5) +
  geom_line(aes(x = days, y = com.median),
            color = "red") +
  facet_wrap(vars(year)) +
  xlab("Days since December 1") + 
  ylab("Whales per day")

```



```{r}

#Com vs Sp
ggplot(data = all.stats) +
  geom_line(aes(x = days, y = sp.median)) +
  geom_ribbon(aes(x = days, 
                  ymin = sp.LCL, 
                  ymax = sp.UCL),
              fill = "orange", alpha = 0.5) + 
  facet_wrap(vars(year))+
  xlab("Days since December 1") + 
  ylab("Whales per day (spline)")



```


```{r}

ggplot(data = all.stats) +
  geom_line(aes(x = days, y = com.median)) +
  geom_ribbon(aes(x = days, 
                  ymin = com.LCL, 
                  ymax = com.UCL),
              fill = "orange", alpha = 0.5) + 
  facet_wrap(vars(year))+
  xlab("Days since December 1") + 
  ylab("Whales per day (Normal)")

```


```{r}

ggplot(data = all.stats) +
  geom_line(aes(x = days, y = Daily.Est.median)) +
  geom_ribbon(aes(x = days, 
                  ymin = Daily.Est.LCL, 
                  ymax = Daily.Est.UCL),
              fill = "orange", 
              alpha = 0.5) + 
  facet_wrap(vars(year))+
  xlab("Days since December 1") + 
  ylab("Whales per day")


```

Total abundance
```{r}
abundance.df <- data.frame(total.median = apply(Corrected.Est, 
                                                FUN = median, 
                                                MARGIN = 2),
                           total.LCL = apply(Corrected.Est, 
                                             MARGIN = 2, 
                                             FUN = quantile, 0.025),
                           total.UCL = apply(Corrected.Est, 
                                             MARGIN = 2, 
                                             FUN = quantile, 0.975),
                           Season = seasons)


ggplot(data = abundance.df) + 
  geom_point(aes(x = Season, y = total.median)) + 
  geom_errorbar(aes(x = Season, ymin = total.LCL, ymax = total.UCL))

#median(apply(exp(sp[,,4]),1,sum))

```

