---
title: "Variance-covariance estimation"
output: html_notebook
---

2023-01-03

R notebook for extracting the variance-covariance matrix of abundance estimates.


```{r setup, include=FALSE}
rm(list = ls())
#knitr::opts_chunk$set(echo = TRUE)
#save.fig <- F

source("Granite_Canyon_Counts_fcns.R")
library(tidyverse)
library(lubridate)
# library(flextable)
library(readr)
library(bayesplot)

# Estimates from Laake et al. are here:
col.defs <- cols(Year = col_character(),
                 Nhat = col_double(),
                 CV = col_double())

Laake.estimates <- read_csv(file = "Data/Laake et al 2012 Table 9 Nhats.csv",
                            col_types = col.defs) %>% 
  mutate(SE = CV * Nhat,
         LCL = Nhat - 1.96 * SE,
         UCL = Nhat + 1.96 * SE,
         Season = lapply(strsplit(Year, "_"), 
                         FUN = function(x) paste0(x[1], "/", x[2])) %>% 
           unlist) %>%
  dplyr::select(Season, Nhat, SE, LCL, UCL)  %>%
  mutate(Year = lapply(str_split(Season, "/"), 
                       FUN = function(x) x[2]) %>% 
           unlist() %>% 
           as.numeric())

# Bring in data from Rugh et al. 2001 (median dates)
Rugh.data <- read_csv(file = "Data/Rugh et al 2001 Table 1 Median Date.txt",
                      col_types = cols(Season = col_character(),
                                       Median_Date = col_date(format = "%Y-%m-%d"))) %>%
  mutate(Year = lapply(str_split(Season, "/"), 
                       FUN = function(x) x[2]) %>% 
           unlist() %>% 
           as.numeric(),
         median.idx = (Median_Date - as.Date(paste0((Year-1), "-12-01"))) %>%
           as.numeric())

# Durban estimates:
Durban.estimates <- data.frame(Year = c(2007, 2008, 2010, 2011, 2015, 2016, 2020, 2022),
                               Season = c("2006/2007", "2007/2008", "2009/2010",
                                          "2010/2011", "2014/2015", "2015/2016",
                                          "2019/2020", "2021/2022"),
                               Nhat = c(20750, 17820, 21210, 20990, 28790, 26960, 20580, 16650),
                               LCL = c(18860, 16150, 19420, 19230, 23620, 24420, 18700, 15170),
                               UCL = c(23320, 19920, 23250, 22900, 39210, 29830, 22870, 18335),
                               Method = "Durban")

# UMEs
UMEs <- data.frame(Season = c("1999/2000", "2000/2001", 
                              "2019/2020", 
                              "2020/2021", "2021/2022"),
                   Year = c(1999, 2000, 2019, 2020, 2021))

# This is for the 2022 analysis. Change it accordingly:
end.year <- 2022
all.years <- data.frame(Year = seq(from = min(Laake.estimates$Year), 
                                  to = end.year))

# Observer list gets updated as new observers are added. 
obs.list <- read.csv("Data/Observer list.csv", header = T) 
colnames(obs.list) <- c("obs", "ID")

seasons <- c("2006/2007", "2007/2008", "2009/2010", "2010/2011", 
             "2014/2015", "2015/2016", "2019/2020", "2021/2022")

x <- length(seasons)

all.files.2022 <- list.files("Data/2022/")
data.first.2022 <- get.data("Data/", 2022, 1)
data.last.2022 <- get.data("Data/", 2022, length(all.files.2022))

data.all.list <- list()
for (k in 1:length(all.files.2022)){
  data.all.list[[k]] <- get.data("Data/", 2022, k) 
}

data.all <- do.call(rbind, data.all.list)

# observers                  
unique.obs <- data.all %>% 
  filter(V2 == "P") %>%
  dplyr::select(V5) %>% 
  unique()

# survey hours
data.all %>% 
  filter(V2 == "B") %>%
  dplyr::select(V2, begin) -> tmp.B

data.all %>% 
  filter(V2 == "E") %>%
  dplyr::select(V2, begin) -> tmp.E

survey.hrs <- 24 * (tmp.E$begin - tmp.B$begin)

data.all %>% 
  dplyr::select(V3) %>%
  mutate(Date = as.Date(V3, format = "%m/%d/%Y")) -> survey.dates 

# sightings
data.all %>% filter(V2 == "S") %>%
  mutate(Date = as.Date(V3, format = "%m/%d/%Y"),
         GroupID = as.numeric(V5), 
         n = as.numeric(V9)) %>%
  dplyr::select(Date, GroupID, n) %>%
  group_by(Date, GroupID) %>% #group by the whale group number
  #summarize(N = max(as.numeric(V9), na.rm = T)) %>% 
  summarize(N = last(n)) -> whale.groups

# daily counts
whale.groups %>%
  group_by(Date) %>%
  summarize(N = sum(N)) -> whale.groups.daily
```


Calculate var-cov matrix

```{r Ver1-data, echo=FALSE, warning=FALSE, message= FALSE}

Ver1.results <- readRDS(paste0("RData/WinBUGS_", x, "yr_v1.rds"))

# Extract posteriors for "Corrected.Est":
post.matrix <- Ver1.results$BUGS_out$sims.matrix
Corrected.Est.posterior <- post.matrix[, grep("Corrected.Est", dimnames(post.matrix)[[2]])]
var.cov <- var(Corrected.Est.posterior)

```


Check to make sure CV for the most recent year matches what I provided in the report. Then, send it to Andre P.



